name: jewellery_billing_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1 # Keeping your specified SDK version

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Firebase Core (already there, updating to a recent stable version)
  firebase_core: ^3.1.0 # Current stable is 3.1.0 as of mid-2025

  # Firebase Services for the app
  cloud_firestore: ^5.0.0 # Latest stable
  firebase_auth: ^5.0.0 # Latest stable

  # State Management
  provider: ^6.1.2 # Latest stable

  # Utilities
  uuid: ^4.4.0 # Latest stable for generating unique IDs
  intl: ^0.18.1 # Latest stable for date/number formatting

  # PDF Generation and Printing
  pdf: ^3.11.0 # Latest stable
  printing: ^5.14.2 # <--- CORRECTED VERSION (was 6.0.0)
  path_provider: ^2.1.3 # Latest stable for saving files to device
  open_filex: ^4.3.4 # Latest stable for opening files after saving

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0 # Keeping your specified lints version

  # FlutterFire CLI (for `flutterfire configure` command)
  flutterfire_cli: ^1.3.1 # Already corrected

flutter:
  uses-material-design: true